### ISSUE TITLE
codecov's S3 upload doesn't report failure but reported URL has no data

### ISSUE THREAD

**Issue by achristoforides** [codecov/codecov-python#222]
After generating a merged coverage report and using codecov to process and upload it, the tool reports that it uploads the result to S3. Additionally, it outputs a URL where the report can be found. In this instance, we're using AppVeyor.

When going to this URL, I'm greeted with the message "Unable to find report content in the storage archive." The page displays another large message asking if the repo is private (which it is not).

The command-line tool doesn't report any errors and the output from the codecov tools is identical to when it was working and provided a link to a page with valid results.

Here is the output of the command:

```
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
abort: no repository found in 'C:\projects\[our project]\build' (.hg not found)!
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.15
==> Detecting CI provider
    AppVeyor Detected
==> Preparing upload
    Error running `cd 'C:\projects\[our project]\build' && git ls-files`: None
    Error running `cd 'C:\projects\[our project]\build' && hg locate`: None
    Error running `hg locate`: None
XX> Skip processing gcov
==> Collecting reports
XX> Searching for reports disabled
    Targeting specific files
    + coverage_pathsfixed.xml bytes=1567145
==> Uploading
    .url https://codecov.io
    .query service=appveyor&package=py2.0.15&job=[our project]%2F[our project]%2F3.99.1084&build=xxxxxxxx&branch=development&commit=xxxxxxxx&slug=[our project]%2F[our project]
    Pinging Codecov...
    Uploading to S3...
    https://codecov.io/github/[our project]/[our project]/commit/xxxxxxxxxx
Build success
```

I'm not sure what could be going wrong but was there a major change in the code recently which would force us to update our config or some other setting?

**Comment by raczben** [comment]
Can you link your repo to see the full settings?

Please read [this SO post](https://stackoverflow.com/q/59934305/2506522), and give the coverage file explicitly.

**Comment by Jeeyuen-Rick** [comment]
I can link the repo. May you tell me what do I look for in the settings?

**Comment by Jeeyuen-Rick** [comment]
I had changed -f switch to --file switch with --no-color and it still failed.

**Comment by Jeeyuen-Rick** [comment]
Our code coverage worked until 4 months ago and the last job that still worked is
https://ci.appveyor.com/project/cppmicroservices/cppmicroservices/builds/28358857/job/gwcwwtj78f6973kw and codecov report still available here https://codecov.io/github/CppMicroServices/CppMicroServices/commit/35e20cc08ae1905c43431440cce8b8cb223dde8c
We encountered problem around the same time (4 months ago) 
https://ci.appveyor.com/project/cppmicroservices/cppmicroservices/builds/28835627/job/ll8vixo85g49b0w9
Since then we got "Unable to find report content in the storage archive." such as the job below.
job is https://ci.appveyor.com/project/cppmicroservices/cppmicroservices/builds/28984292/job/254i0gsfbirl1shi 
report is https://codecov.io/github/CppMicroServices/CppMicroServices/commit/7b52817f2d7d152abaffdf0850d944f5696ffa23

We are not sure what caused the failure. Any suggestion is appreciated.

**Comment by Jeeyuen-Rick** [comment]
We fixed our problem with the following changes:

1. specify gcov version same as gcc version, codecov requires both gcc and gcov have the same version on Linux
2. use codecov bash script on AppVeyor machine image install of local installed codecov to get invalid syntax error on Windows
3. remove spaces from code coverage pathname with spaces for Linux build
4. Add extra line after last method close bracket (}) between namespace close bracket (}) for short program. gcov has problem reading the two brackets right after one another on Linux for program with 18 lines or less.

We don't have any problem before even there're Linux and Windows build issues. Please feel free to close this issue.
