### ISSUE TITLE
Tags and changelog for 2.1.x?

### ISSUE THREAD

**Issue by timmc-edx** [codecov/codecov-python#256]
It looks like 2.1.0 and 2.1.1 have hit PyPI, but I don't see tags in git. (2.0.22 is also missing from the changelog.) Would you mind pushing these up?

**Comment by drazisil** [comment]
I have no idea what `2.0.22` changed.

2.1.0 was to remove a header that was causing 400s on upload.

... These were small bug fixes that I'm blanking on right now. Will research when I get a chance.

2.1.3 was to replace `find` with a native find. It was also to correct version numbers since I believe all prior 2.1.x versions reported as 2.0.24?

**Comment by thomasrockhu** [comment]
This has been done via https://github.com/codecov/codecov-python/pull/271
