### ISSUE TITLE
Bash Uploader security concern

### ISSUE THREAD

**Issue by dinvlad** [codecov/codecov-python#316]
Hi Team,

Could you confirm that this library is unaffected by the recently disclosed https://about.codecov.io/security-update/ ?

Thanks

**Comment by thomasrockhu** [comment]
Hi @dinvlad, Tom from Codecov here. Confirming that this library was *not affected* by the recent security issue.

**Comment by hootener** [comment]
A question came across our support emails that asked this question:

> What reviews did you complete to ensure the python package not impacted

and linked to this issue.

I feel that in the interest of transparency, it's worth answering that question here so that it can be consumed by the wider community. If you read this, and have questions about _your specific use of Codecov_ , I would still urge you to send those questions to security@codecov.io. 

For the python uploader to be impacted in a manner similar to the bash uploader, it would have had to have been modified either here, on GitHub, or at the distribution layer on pypi. 

We did a full audit of our entire github organization, associated users, logins, and tokens to confirm that no malicious access directly to github was obtained. There are also no malicious PRs, commits, etc in this repository that insert code into the python uploader that could carry out an attack similar to what we disclosed for codecov-bash. Additionally, [the last pypi release ](https://pypi.org/project/codecov/#history) of the python uploader was Dec 17, 2020. which was six weeks before the first instance of this attack on the bash uploader, and [was a release pushed by a Codecov team member](https://github.com/codecov/codecov-python/releases).
