### ISSUE TITLE
Detect report timestamps before uploading

### ISSUE THREAD

**Issue by stevepeak** [codecov/codecov-python#42]
A customer experienced an issue when the uploaded report had expires (being that it was > 12 hours old). The uploader should (1) recognize these files, (2) make note of them not being uploaded, (3) proceed to call `coverage xml` if necessary.

**Comment by slafs** [comment]
Hello. Would like to ask if there's any progress on this?

**Comment by stevepeak** [comment]
I'll see to adding it in my next hack, there are a couple different ways the timestamp is presented in different reports. Adding this is important for sure ;)

**Comment by zbeekman** [comment]
Just FYI, currently the time shown on the website next to the commit hash (age of commit/coverage) is off by a number of hours. It may not be related to this issue, and I suspect it is due to git/travis/etc reporting time in UTC and some other system reporting time in the current TZ... or something like that... just a hunch because my TZ is about 5 or 6 hours off of UTC depending on daylight savings, which appears to be the differential I am seeing online.

**Comment by thomasrockhu** [comment]
Closing out due to age, and I believe is no longer an issue.
