### ISSUE TITLE
Why does codecov use verify=False when upoading to S3?

### ISSUE THREAD

**Issue by alex** [codecov/codecov-python#50]
This allows an attacker to see the results or manipulate them.

cc: @reaperhulk, @dstufft

**Comment by stevepeak** [comment]
Hey @alex there was an issue that kept repeating on Travis where the upload failed due to the generic SSL exception. I don't have specific examples however. I'm not sure if it was a service outage or something else, but adding verify=False fixed the issue.

I've been planning on doing the following:
```py
try:
    res = request.put(S3)
    res.raise_for_status() 
except:
    res = request.put(S3, verify=False)
    res.raise_for_status()
....
```

**Comment by stevepeak** [comment]
Deployed
