### ISSUE TITLE
coverage parallel not supported

### ISSUE THREAD

**Issue by jayvdb** [codecov/codecov-python#72]
When coverage run config `parallel = True`, cmdline option `-p`, `--parallel-mode`, multiple coverage data files are created with machine name, process id and random number appended to the .coverage data file name.

codecov reports "No coverage report found".

**Comment by stevepeak** [comment]
How does your sequence of test commands look like? There should be no issue with this.

Can you run `coverage combine && coverage xml` after your tests to check if a coverage.xml file is generated. Thanks!

**Comment by jayvdb** [comment]
Yea, `coverage combine` is a workaround, but it would be nice if `codecov` found them.

**Comment by stevepeak** [comment]
Will deploy in next release 👍

**Comment by gilmrjc** [comment]
This breaks the reporting of my tests. In my Travis config I combine my data like this

```
script:
  - coverage erase
  - tox --skip-missing
  - coverage combine
  - coverage report --fail-under 80
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

The problem is when you run ```coverage combine``` twice the coverage data is not longer available. I need to combine my coverage to fail if the threshold fails. It's better to do the ```combine``` in the CI and not in the codecov-bash, because I can add or remove it with my configuration files, or if this can be set with some kind of flag to avoid breaking the reporting.

**Comment by jayvdb** [comment]
@gilmrjc wrote
> The problem is when you run coverage combine twice the coverage data is not longer available.

It seems this is the main problem?  And it is possibly a bug upstream?

I agree that some people need to be able to run `coverage combine` themselves, and the codecov client app should still work in that scenario.

Unrelated, looking at the change 2cff906341, is this portable?

```coverage combine && coverage xml -i```

i.e. does `&&` work on Windows?

**Comment by gilmrjc** [comment]
This is not a bug in coverage. When you run coverage in parallel mode it creates a coverage file for each environment + set of tests. When you combine them coverage merge the data and deletes the files. Without deleting them coverage can distinct between older tests coverage and the current tests coverage.

When you run combine again coverage doesn't find the specific coverage files because they don't exist and generates an empty coverage file with no data. The problem is that you should call combine explicitly, and once a script you don't own runs it you break the workflow.

What the client should do is run coverage xml and if no data is found run coverage combine && coverage xml as a fallback.

**Comment by jayvdb** [comment]
The bug/improvement in `coverage combine` would be that when it doesnt find multiple coverage files, but does find a normal coverage file, it doesnt create an empty coverage file.

What is the benefit of `coverage combine` replacing one coverage file with an empty coverage file...?

However, I see at https://bitbucket.org/ned/coveragepy/issues/511/version-42-coverage-combine-empties that this is at least partially intended behaviour introduced for coverage 4.2+

And the solution there is to use `coverage combine --append` on coverage 4.2+ if we dont want to overwrite the existing coverage data file.

I have raised https://bitbucket.org/ned/coveragepy/issues/516/running-coverage-combine-twice-deletes-all about the side-effect we are experiencing.

> What the client should do is run coverage xml and if no data is found run coverage combine && coverage xml as a fallback. 

Aye, that could work.

Another approach is for `codecov` to check for `.coverage` /  `.coverage.*` files, and then only run `coverage combine` if there are partial coverage files and no unified `.coverage`.
It can then also emit messages if it finds both, which suggests that some partial coverage data needs to be appended, but IMO codecov shouldnt automatically do that merge.  (I would be happy to write the PR for this approach.)

**Comment by stevepeak** [comment]
@jayvdb that would be great! I do believe there are those whom are still using coveragepy 3.0.7 so relying on v4 is not entirely possible.

**Comment by stevepeak** [comment]
@jayvdb does this work for the bash uploader: https://github.com/codecov/codecov-bash/commit/08e55732b4b323ca8e9a1c818be421d3d671b3a2

**Comment by jayvdb** [comment]
It looks good, but I dont have any projects that use codecov-bash to test with easily.

**Comment by gilmrjc** [comment]
@stevepeak the bash version works. The project I have using codecov bash now sends the reports even if I run combine before :)

**Comment by jayvdb** [comment]
> I have raised https://bitbucket.org/ned/coveragepy/issues/516/running-coverage-combine-twice-deletes-all
> about the side-effect we are experiencing.

This has been fixed, but not yet released.
So in the next release, running `coverage combine` will be an error when there are no parallel files yet to be combined.

**Comment by stevepeak** [comment]
@jayvdb @gilmrjc ^^ 

Thanks friends 👍 I'll look into publishing the codecov-python uploader today if it lgty
